n=input("What's your name? ")
print("Hello, ", n)
a=input("How old are you? ")
print("Your age is ", a)
l=input("Where do you live?  ")
print("You live in ", l)

a=int(input("Input a: "))
b=int(input("Input b: "))
print("a+b=", a+b)
print("a-b=", a-b)
print("a*b=", a*b)
print("a/b=", a/b)
print("a**b=", a**b)
